server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quiz_db?createDatabaseIfNotExist=true
    username: root
    password: my1234
  jpa:
    hibernate:
      ddl-auto: update
